'use strict';

angular.module('matdiskApp')
  .factory('Negara', function () {
    return [
      {'negara': 'Albania', 'kodeNegara': 'AL', 'kode': 28},
      {'negara': 'Andora', 'kodeNegara': 'AD', 'kode': 24},
      {'negara': 'Austria', 'kodeNegara': 'AT', 'kode': 20},
      {'negara': 'Azerbaijam', 'kodeNegara': 'AZ', 'kode': 28},
      {'negara': 'Belgium', 'kodeNegara': 'BE', 'kode': 16},
      {'negara': 'Bahrain', 'kodeNegara': 'BH', 'kode': 22},
      {'negara': 'Bosnia', 'kodeNegara': 'BA', 'kode': 20},
      {'negara': 'Brazil', 'kodeNegara': 'BR', 'kode': 29},
      {'negara': 'Bulgaria', 'kodeNegara': 'BG', 'kode': 22},
      {'negara': 'Costa Rica', 'kodeNegara': 'CR', 'kode': 21},
      {'negara': 'Croatia', 'kodeNegara': 'HR', 'kode': 21},
      {'negara': 'Cyprus', 'kodeNegara': 'CY', 'kode': 28},
      {'negara': 'Czech Republic', 'kodeNegara': 'CZ', 'kode': 24},
      {'negara': 'Denmark', 'kodeNegara': 'DK', 'kode': 18},
      {'negara': 'Dominican Republic', 'kodeNegara': 'DO', 'kode': 28},
      {'negara': 'Estonia', 'kodeNegara': 'EE', 'kode': 20},
      {'negara': 'Faroe Islands', 'kodeNegara': 'FO', 'kode': 18},
      {'negara': 'Finland', 'kodeNegara': 'FI', 'kode': 18},
      {'negara': 'France', 'kodeNegara': 'FR', 'kode': 27},
      {'negara': 'Georgia', 'kodeNegara': 'GE', 'kode': 22},
      {'negara': 'Germany', 'kodeNegara': 'DE', 'kode': 22},
      {'negara': 'Gibraltar', 'kodeNegara': 'GI', 'kode': 23},
      {'negara': 'Greece', 'kodeNegara': 'GR', 'kode': 27},
      {'negara': 'Greenland', 'kodeNegara': 'GL', 'kode': 18},
      {'negara': 'Guatemala', 'kodeNegara': 'GT', 'kode': 28},
      {'negara': 'Hungary', 'kodeNegara': 'HU', 'kode': 28},
      {'negara': 'Iceland', 'kodeNegara': 'IS', 'kode': 26},
      {'negara': 'Ireland', 'kodeNegara': 'IE', 'kode': 22},
      {'negara': 'Israel', 'kodeNegara': 'IL', 'kode': 23},
      {'negara': 'Italy', 'kodeNegara': 'IT', 'kode': 27},
      {'negara': 'Kazakhstan', 'kodeNegara': 'KZ', 'kode': 20},
      {'negara': 'Kuwait', 'kodeNegara': 'KW', 'kode': 30},
      {'negara': 'Latvia', 'kodeNegara': 'LV', 'kode': 21},
      {'negara': 'Lebanon', 'kodeNegara': 'LB', 'kode': 28},
      {'negara': 'Liechtenstein', 'kodeNegara': 'LI', 'kode': 21},
      {'negara': 'Lithuania', 'kodeNegara': 'LT', 'kode': 20},
      {'negara': 'Luxembourg', 'kodeNegara': 'LU', 'kode': 20},
      {'negara': 'Macedonia', 'kodeNegara': 'MK', 'kode': 19},
      {'negara': 'Malta', 'kodeNegara': 'MT', 'kode': 31},
      {'negara': 'Mauritania', 'kodeNegara': 'MR', 'kode': 27},
      {'negara': 'Mauritius', 'kodeNegara': 'MU', 'kode': 30},
      {'negara': 'Monaco', 'kodeNegara': 'MC', 'kode': 27},
      {'negara': 'Moldova', 'kodeNegara': 'MD', 'kode': 24},
      {'negara': 'Montenegro', 'kodeNegara': 'ME', 'kode': 22},
      {'negara': 'Netherlands', 'kodeNegara': 'NL', 'kode': 18},
      {'negara': 'Norway', 'kodeNegara': 'NO', 'kode': 15},
      {'negara': 'Pakistan', 'kodeNegara': 'PK', 'kode': 24},
      {'negara': 'Palestinian', 'kodeNegara': 'PS', 'kode': 29},
      {'negara': 'Poland', 'kodeNegara': 'PL', 'kode': 28},
      {'negara': 'Portugal', 'kodeNegara': 'PT', 'kode': 25},
      {'negara': 'Romania', 'kodeNegara': 'RO', 'kode': 24},
      {'negara': 'San Marino', 'kodeNegara': 'SM', 'kode': 27},
      {'negara': 'Saudi Arabia', 'kodeNegara': 'SA', 'kode': 24},
      {'negara': 'Serbia', 'kodeNegara': 'RS', 'kode': 22},
      {'negara': 'Slovakia', 'kodeNegara': 'SK', 'kode': 24},
      {'negara': 'Slovenia', 'kodeNegara': 'SI', 'kode': 19},
      {'negara': 'Spain', 'kodeNegara': 'ES', 'kode': 24},
      {'negara': 'Sweden', 'kodeNegara': 'SE', 'kode': 24},
      {'negara': 'Switzerland', 'kodeNegara': 'CH', 'kode': 21},
      {'negara': 'Tunisia', 'kodeNegara': 'TN', 'kode': 24},
      {'negara': 'Turkey', 'kodeNegara': 'TR', 'kode': 26},
      {'negara': 'United Arab emirates', 'kodeNegara': 'AE', 'kode': 23},
      {'negara': 'United Kingdom', 'kodeNegara': 'GB', 'kode': 22},
      {'negara': 'Virgin Island British', 'kodeNegara': 'VG', 'kode': 24}
    ];
  })
  .controller('MainCtrl', function ($scope, Negara){
    $scope.Negara = Negara;
  })
;
